<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <AssemblyName>MetroidvaniaStudio.Core</AssemblyName>
    <RootNamespace>MetroidvaniaStudio</RootNamespace>
    <NuGetAudit>false</NuGetAudit>
    <RestoreIgnoreFailedSources>true</RestoreIgnoreFailedSources>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="../Localization/MetroidvaniaStudioLocale.csv" LogicalName="MetroidvaniaStudioLocale.csv" />
  </ItemGroup>
</Project>
