// <auto-generated> Shared map and resource DTOs. Run MetroidvaniaStudio/build-web.mjs.
using System;
using System.Collections.Generic;
namespace MetroidvaniaStudio.Integration
{
    public struct StudioGridPoint { public int x, y; public StudioGridPoint(int x, int y) { this.x = x; this.y = y; } }
    [Serializable] public sealed class CameraProfile
    {
        public int ppu = 16;
        public int referenceWidth = 320;
        public int referenceHeight = 180;
        public float orthographicSize = 5.625f;
        public float x = 0f;
        public float y = 0f;
    }

    [Serializable] public sealed class CatalogData
    {
        public List<MaterialData> materials = new List<MaterialData>();
        public List<ObjectData> objects = new List<ObjectData>();
        public CameraProfile camera = null;
    }

    [Serializable] public sealed class MapCell
    {
        public int x = 0;
        public int y = 0;
        public TileShape shape = (TileShape)0;
        public string material = "terrain";
        public string groupId = "";
    }

    [Serializable] public sealed class MapDocument
    {
        public int formatVersion = 2;
        public int tileSize = 16;
        public string name = "Untitled";
        public List<MapRoom> rooms = new List<MapRoom>();
        public List<MapProperty> properties = new List<MapProperty>();
        public List<MapStyleground> stylegrounds = new List<MapStyleground>();
        public List<MapLayerGroup> layerGroups = new List<MapLayerGroup>();
    }

    [Serializable] public sealed class MapFieldDefinition
    {
        public string key = "field";
        public string label = "Field";
        public MapFieldKind kind = (MapFieldKind)0;
        public string defaultValue = "";
        public bool required = false;
        public double min = -1.7976931348623157E+308;
        public double max = 1.7976931348623157E+308;
        public string[] choices = new string[0];
    }

    public enum MapFieldKind { String = 0, Integer = 1, Number = 2, Boolean = 3, Color = 4, Choice = 5, Path = 6 }

    public enum MapLayer { ForegroundTiles = 0, BackgroundTiles = 1, Entities = 2, Triggers = 3, ForegroundDecals = 4, BackgroundDecals = 5, All = 6 }

    [Serializable] public sealed class MapLayerGroup
    {
        public string id = "";
        public string name = "Group";
        public MapLayer layer = (MapLayer)0;
        public string parentId = "";
        public bool visible = true;
        public bool locked = false;
    }

    [Serializable] public sealed class MapObject
    {
        public string id = "";
        public string definition = "object";
        public MapLayer layer = (MapLayer)2;
        public string groupId = "";
        public float x = 0f;
        public float y = 0f;
        public float width = 1f;
        public float height = 1f;
        public float rotation = 0f;
        public float scaleX = 1f;
        public float scaleY = 1f;
        public List<StudioPoint> nodes = new List<StudioPoint>();
        public List<MapProperty> properties = new List<MapProperty>();
    }

    [Serializable] public sealed class MapProperty
    {
        public string key = "";
        public string value = "";
    }

    [Serializable] public sealed class MapRoom
    {
        public string id = "";
        public string name = "room_00";
        public int x = 0;
        public int y = 0;
        public int width = 40;
        public int height = 24;
        public bool visible = true;
        public bool locked = false;
        public List<MapCell> foreground = new List<MapCell>();
        public List<MapCell> background = new List<MapCell>();
        public List<MapObject> objects = new List<MapObject>();
        public List<MapProperty> properties = new List<MapProperty>();
    }

    [Serializable] public sealed class MapStyleground
    {
        public string id = "";
        public string name = "Styleground";
        public string type = "parallax";
        public MapLayer layer = (MapLayer)5;
        public string texture = "";
        public string color = "#FFFFFF";
        public float scrollX = 1f;
        public float scrollY = 1f;
        public List<MapProperty> properties = new List<MapProperty>();
    }

    [Serializable] public sealed class MaterialData
    {
        public string id = null;
        public string name = null;
        public string color = null;
        public string themeId = null;
        public List<SpriteData> sprites = new List<SpriteData>();
    }

    [Serializable] public sealed class ObjectData
    {
        public string id = null;
        public string name = null;
        public string color = null;
        public int layer = 0;
        public int placement = 0;
        public int minimumNodes = 0;
        public int maximumNodes = 0;
        public float width = 0f;
        public float height = 0f;
        public float minimumWidth = 0f;
        public float minimumHeight = 0f;
        public bool resizable = false;
        public bool rotatable = false;
        public bool flippable = false;
        public SpriteData sprite = null;
        public List<MapFieldDefinition> properties = new List<MapFieldDefinition>();
    }

    [Serializable] public sealed class SpriteData
    {
        public string asset = null;
        public int x = 0;
        public int y = 0;
        public int width = 0;
        public int height = 0;
        public int mask = 0;
        public int shape = 0;
    }

    [Serializable] public sealed class StudioPoint
    {
        public float x = 0f;
        public float y = 0f;
        public StudioPoint() {}
        public StudioPoint(float x, float y) { this.x = x; this.y = y; }
    }

    public enum TileShape { Solid = 0, BottomLeft = 1, BottomRight = 2, TopLeft = 3, TopRight = 4 }
}
