// <auto-generated> Shared autotile geometry.
using System;
using System.Collections.Generic;


namespace MetroidvaniaStudio.Integration
{
    /// <summary>Eight-neighbor blob masks, with corner bits gated by their two sides.</summary>
    public static class TileMask
    {
        public const int N = 1;
        public const int NE = 2;
        public const int E = 4;
        public const int SE = 8;
        public const int S = 16;
        public const int SW = 32;
        public const int W = 64;
        public const int NW = 128;

        public static int Normalize(int mask)
        {
            mask &= 255;
            if ((mask & (N | E)) != (N | E)) mask &= ~NE;
            if ((mask & (E | S)) != (E | S)) mask &= ~SE;
            if ((mask & (S | W)) != (S | W)) mask &= ~SW;
            if ((mask & (W | N)) != (W | N)) mask &= ~NW;
            return mask;
        }

        public static int[] GetValidMasks()
        {
            var masks = new List<int>(47);
            for (int mask = 0; mask < 256; mask++)
            {
                if (Normalize(mask) == mask)
                    masks.Add(mask);
            }
            return masks.ToArray();
        }

        /// <summary>
        /// Cardinal connections require a full shared side. Diagonal connections
        /// require a shared corner; Normalize subsequently gates them by the sides.
        /// </summary>
        public static bool Connects(TileShape center, TileShape neighbor, StudioGridPoint offset)
        {
            if (offset.x < -1 || offset.x > 1 || offset.y < -1 || offset.y > 1)
                return false;
            if (offset.x == 0 && offset.y == 0)
                return false;

            if (offset.x != 0 && offset.y != 0)
                return HasCorner(center, offset.x, offset.y) && HasCorner(neighbor, -offset.x, -offset.y);

            return HasSide(center, offset.x, offset.y) && HasSide(neighbor, -offset.x, -offset.y);
        }

        /// <summary>Counter-clockwise vertices centered on a one-unit cell.</summary>
        public static StudioPoint[] GetPolygon(TileShape shape)
        {
            var bottomLeft = new StudioPoint(-0.5f, -0.5f);
            var bottomRight = new StudioPoint(0.5f, -0.5f);
            var topRight = new StudioPoint(0.5f, 0.5f);
            var topLeft = new StudioPoint(-0.5f, 0.5f);
            switch (shape)
            {
                case TileShape.Solid: return new[] { bottomLeft, bottomRight, topRight, topLeft };
                case TileShape.BottomLeft: return new[] { bottomLeft, bottomRight, topLeft };
                case TileShape.BottomRight: return new[] { bottomLeft, bottomRight, topRight };
                case TileShape.TopLeft: return new[] { bottomLeft, topRight, topLeft };
                case TileShape.TopRight: return new[] { bottomRight, topRight, topLeft };
                default: throw new ArgumentOutOfRangeException(nameof(shape), shape, "Unknown tile shape.");
            }
        }

        private static bool HasSide(TileShape shape, int x, int y)
        {
            switch (shape)
            {
                case TileShape.Solid: return true;
                case TileShape.BottomLeft: return x < 0 || y < 0;
                case TileShape.BottomRight: return x > 0 || y < 0;
                case TileShape.TopLeft: return x < 0 || y > 0;
                case TileShape.TopRight: return x > 0 || y > 0;
                default: return false;
            }
        }

        private static bool HasCorner(TileShape shape, int x, int y)
        {
            switch (shape)
            {
                case TileShape.Solid: return true;
                case TileShape.BottomLeft: return x < 0 || y < 0;
                case TileShape.BottomRight: return x > 0 || y < 0;
                case TileShape.TopLeft: return x < 0 || y > 0;
                case TileShape.TopRight: return x > 0 || y > 0;
                default: return false;
            }
        }
    }
}
