using System.Globalization;
using System.Reflection;
using System.Text;
using System.Text.Json;
using MetroidvaniaStudio;

internal static class IntegrationContracts
{
    public static bool Write(string repository, bool check)
    {
        var pending = new Queue<Type>(new[] { typeof(MapDocument), typeof(CatalogData) });
        var definitions = new SortedDictionary<string, string>(StringComparer.Ordinal);
        string TypeName(Type type)
        {
            if (type == typeof(string)) return "string";
            if (type == typeof(bool)) return "bool";
            if (type == typeof(int)) return "int";
            if (type == typeof(float)) return "float";
            if (type == typeof(double)) return "double";
            if (type.IsArray) return TypeName(type.GetElementType()!) + "[]";
            if (type.IsGenericType && type.GetGenericTypeDefinition() == typeof(List<>)) return "List<" + TypeName(type.GetGenericArguments()[0]) + ">";
            pending.Enqueue(type);
            return type.Name == "Vector2" ? "StudioPoint" : type.Name;
        }
        while (pending.TryDequeue(out Type? type))
        {
            string name = type.Name == "Vector2" ? "StudioPoint" : type.Name;
            if (definitions.ContainsKey(name)) continue;
            if (type.IsEnum)
            {
                definitions[name] = "    public enum " + name + " { " + string.Join(", ", Enum.GetNames(type).Select(value => value + " = " + Convert.ToInt32(Enum.Parse(type, value)))) + " }\n";
                continue;
            }
            object instance = Activator.CreateInstance(type)!;
            var body = new StringBuilder("    [Serializable] public sealed class " + name + "\n    {\n");
            foreach (FieldInfo field in type.GetFields(BindingFlags.Public | BindingFlags.Instance).Where(f => !f.IsInitOnly && !f.IsDefined(typeof(NonSerializedAttribute))))
            {
                Type valueType = field.FieldType;
                string valueName = TypeName(valueType);
                object? value = field.GetValue(instance);
                string initializer = valueType == typeof(string) ? (value == null ? "null" : JsonSerializer.Serialize((string)value))
                    : valueType == typeof(bool) ? ((bool)value! ? "true" : "false")
                    : valueType.IsEnum ? "(" + valueName + ")" + Convert.ToInt32(value)
                    : valueType.IsPrimitive ? Convert.ToString(value, CultureInfo.InvariantCulture)! + (valueType == typeof(float) ? "f" : "")
                    : value == null ? "null" : valueType.IsArray ? "new " + TypeName(valueType.GetElementType()!) + "[0]" : "new " + valueName + "()";
                if (field.Name == "id" && value is string id && Guid.TryParseExact(id, "N", out _)) initializer = "\"\"";
                body.Append("        public " + valueName + " " + field.Name + " = " + initializer + ";\n");
            }
            if (name == "StudioPoint") body.Append("        public StudioPoint() {}\n        public StudioPoint(float x, float y) { this.x = x; this.y = y; }\n");
            definitions[name] = body.Append("    }\n").ToString();
        }
        string content = "// <auto-generated> Shared map and resource DTOs. Run metroidvania-studio/build-web.mjs.\nusing System;\nusing System.Collections.Generic;\nnamespace MetroidvaniaStudio.Integration\n{\n    public struct StudioGridPoint { public int x, y; public StudioGridPoint(int x, int y) { this.x = x; this.y = y; } }\n" + string.Join("\n", definitions.Values) + "}\n";
        string camera = File.ReadAllText(Path.Combine(repository, "metroidvania-studio/core/workspace/MapCameraSettings.cs"))
            .Replace("\r\n", "\n").Replace("namespace " + typeof(MapDocument).Namespace + "\n", "namespace MetroidvaniaStudio.Integration\n");
        string mask = File.ReadAllText(Path.Combine(repository, "metroidvania-studio/core/resources/TileMask.cs")).Replace("\r\n", "\n")
            .Replace("using MetroidvaniaStudio.Primitives;", "")
            .Replace("Vector2Int", "StudioGridPoint").Replace("Vector2", "StudioPoint")
            .Replace("namespace " + typeof(MapDocument).Namespace + "\n", "namespace MetroidvaniaStudio.Integration\n");
        string target = Path.Combine(repository, "integrations/unity/Assets/metroidvania-studio-integration/runtime");
        bool current = Save(Path.Combine(target, "StudioContracts.generated.cs"), content, check);
        current &= Save(Path.Combine(target, "MapCameraSettings.generated.cs"), "// <auto-generated> Shared camera settings.\n" + camera, check);
        current &= Save(Path.Combine(target, "TileMask.generated.cs"), "// <auto-generated> Shared autotile geometry.\n" + mask, check);
        return current;
    }
    private static bool Save(string path, string text, bool check)
    {
        text = text.Replace("\r\n", "\n");
        if (File.Exists(path) && File.ReadAllText(path).Replace("\r\n", "\n") == text) return true;
        if (check) { Console.Error.WriteLine("Integration contracts are stale."); return false; }
        Directory.CreateDirectory(Path.GetDirectoryName(path)!); File.WriteAllText(path, text, new UTF8Encoding(false)); return true;
    }
}
