using System.Reflection;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using MetroidvaniaStudio.Server;
using MetroidvaniaStudio;
using MetroidvaniaStudio.Primitives;

// Reflect compiled production types, not a second hand-maintained schema or a
// regex parser. Fail on unsupported members rather than silently emit `any`.
bool check = args.Contains("--check");
string output = args.FirstOrDefault(value => !value.StartsWith("--", StringComparison.Ordinal))
    ?? throw new ArgumentException("Pass the output contracts.generated.ts path (and optionally --check).");
var names = new Dictionary<Type, string>
{
    [typeof(Vector2)] = "Point", [typeof(EditorRect)] = "Rect", [typeof(MapCell)] = "Cell",
    [typeof(MapProperty)] = "Property", [typeof(MapRoom)] = "Room", [typeof(MapLayerGroup)] = "Group",
    [typeof(SpriteData)] = "SpriteRect", [typeof(MaterialData)] = "Material",
    [typeof(ObjectData)] = "Definition", [typeof(MapFieldDefinition)] = "ObjectField",
    [typeof(CameraProfile)] = "CameraProfile", [typeof(CatalogData)] = "Catalog",
    [typeof(EditorSelection)] = "Selection", [typeof(EditorConnection)] = "Connection"
};
var pending = new Queue<Type>(new[] { typeof(EditorState) });
var definitions = new SortedDictionary<string, string>(StringComparer.Ordinal);
var nullability = new NullabilityInfoContext();
while (pending.TryDequeue(out Type? type))
{
    string name = Name(type);
    if (definitions.ContainsKey(name)) continue;
    var body = new StringBuilder($"export interface {name} {{\n");
    // Map JSON serializes public fields, while HTTP DTOs serialize properties. Keep
    // these ownership rules explicit so convenience getters cannot leak in.
    IEnumerable<MemberInfo> members = type.Assembly == typeof(EditorState).Assembly
        ? type.GetProperties(BindingFlags.Public | BindingFlags.Instance).Where(p => p.GetMethod != null)
        : type.GetFields(BindingFlags.Public | BindingFlags.Instance)
            .Where(f => !f.IsInitOnly && !f.IsDefined(typeof(NonSerializedAttribute))
                && f.IsPublic);
    foreach (MemberInfo member in members.OrderBy(member => member.Name, StringComparer.Ordinal))
    {
        if (member.GetCustomAttribute<JsonIgnoreAttribute>()?.Condition == JsonIgnoreCondition.Always) continue;
        Type memberType = member is PropertyInfo property ? property.PropertyType : ((FieldInfo)member).FieldType;
        bool optional = member.GetCustomAttribute<JsonIgnoreAttribute>()?.Condition == JsonIgnoreCondition.WhenWritingNull;
        NullabilityState nullable = member is PropertyInfo prop ? nullability.Create(prop).ReadState : nullability.Create((FieldInfo)member).ReadState;
        Type actualType = member.GetCustomAttribute<WireTypeAttribute>()?.Type ?? Nullable.GetUnderlyingType(memberType) ?? memberType;
        string fieldType = Reference(actualType);
        bool canBeNull = nullable == NullabilityState.Nullable || Nullable.GetUnderlyingType(memberType) != null;
        // WhenWritingNull is absent from the wire, not an explicit JSON null.
        if (canBeNull && !optional) fieldType += " | null";
        string wireName = member.GetCustomAttribute<JsonPropertyNameAttribute>()?.Name ?? member.Name;
        body.Append($"  {wireName}{(optional ? "?" : "")}: {fieldType};\n");
    }
    definitions.Add(name, body.Append("}\n").ToString());
}
var result = new StringBuilder("// <auto-generated> C# wire contracts. Run metroidvania-studio/build-web.mjs; do not edit.\n");
result.Append("// Source: core/workspace/MapDocument and core/resources/CatalogData and server/EditorContracts.\n\n");
foreach (string value in definitions.Values) result.Append(value).Append('\n');
AppendEnum<MetroidvaniaStudioTool>("TOOLS"); AppendEnum<MapLayer>("LAYERS"); AppendEnum<TileShape>("SHAPES");
result.Append($"export const MAX_BRUSH_SIZE = {MapBrushGeometry.MaximumBrushSize};\n");
result.Append($"export const MAP_FORMAT_VERSION = {MapDocument.CurrentFormatVersion};\n");
result.Append($"export const TILE_SIZE = {MapDocument.RequiredTileSize};\n");
string generated = result.ToString();
if (!IntegrationContracts.Write(Path.GetFullPath(Path.Combine(Path.GetDirectoryName(Path.GetFullPath(output))!, "../..")), check)) return 1;
bool schemaCurrent = MapSchema.Write(Path.GetFullPath(Path.Combine(Path.GetDirectoryName(Path.GetFullPath(output))!, "../contracts/map-format-v2.schema.json")), check);
string? current = File.Exists(output) ? File.ReadAllText(output).Replace("\r\n", "\n") : null;
if (current == generated) { Console.WriteLine("C# / TypeScript contracts are current."); return schemaCurrent ? 0 : 1; }
if (check) { Console.Error.WriteLine("C# / TypeScript contracts are stale. Run metroidvania-studio/build-web.mjs."); return 1; }
Directory.CreateDirectory(Path.GetDirectoryName(Path.GetFullPath(output))!);
File.WriteAllText(output, generated, new UTF8Encoding(false));
Console.WriteLine("Generated " + output);
return 0;

string Name(Type type) => names.GetValueOrDefault(type, type.Name);
string Reference(Type type)
{
    if (type == typeof(string)) return "string";
    if (type == typeof(bool)) return "boolean";
    if (type.IsEnum || type == typeof(int) || type == typeof(long) || type == typeof(float) || type == typeof(double)) return "number";
    if (type.IsArray) return Reference(type.GetElementType()!) + "[]";
    if (type.IsGenericType && type.GetGenericTypeDefinition() == typeof(List<>)) return Reference(type.GetGenericArguments()[0]) + "[]";
    if (type != typeof(Vector2) && type.Assembly != typeof(MapDocument).Assembly && type.Assembly != typeof(EditorState).Assembly)
        throw new NotSupportedException("Unsupported wire type: " + type.FullName);
    if (type == typeof(object) || type.IsInterface || type.IsAbstract) throw new NotSupportedException("Unspecified wire type: " + type.FullName);
    pending.Enqueue(type);
    return Name(type);
}
void AppendEnum<T>(string name) where T : struct, Enum
{
    T[] values = Enum.GetValues<T>();
    if (values.Where((value, index) => Convert.ToInt32(value) != index).Any())
        throw new InvalidOperationException(name + " must have contiguous zero-based wire values.");
    result.Append($"export const {name} = {JsonSerializer.Serialize(values.Select(value => value.ToString()))};\n");
}
