// <auto-generated> C# wire contracts. Run metroidvania-studio/build-web.mjs; do not edit.
// Source: core/workspace/MapDocument and core/resources/CatalogData and server/EditorContracts.

export interface CameraProfile {
  orthographicSize: number;
  ppu: number;
  referenceHeight: number;
  referenceWidth: number;
  x: number;
  y: number;
}

export interface Catalog {
  camera: CameraProfile;
  materials: Material[];
  objects: Definition[];
}

export interface Cell {
  groupId: string;
  material: string;
  shape: number;
  x: number;
  y: number;
}

export interface Connection {
  coordinate: number;
  end: number;
  roomAId: string;
  roomBId: string;
  start: number;
  vertical: boolean;
}

export interface Definition {
  color: string;
  flippable: boolean;
  height: number;
  id: string;
  layer: number;
  maximumNodes: number;
  minimumHeight: number;
  minimumNodes: number;
  minimumWidth: number;
  name: string;
  placement: number;
  properties: ObjectField[];
  resizable: boolean;
  rotatable: boolean;
  sprite: SpriteRect | null;
  width: number;
}

export interface EditorExportStatus {
  error: string | null;
  hash: string | null;
  path: string | null;
  phase: string;
  roomId: string | null;
  version: number;
}

export interface EditorNodeSelection {
  id: string;
  index: number;
}

export interface EditorState {
  camera: CameraProfile;
  canRedo: boolean;
  canUndo: boolean;
  catalog?: Catalog;
  catalogRevision: number;
  connections?: Connection[];
  dirty: boolean;
  document?: MapDocument;
  documentRevision: number;
  export: EditorExportStatus;
  file: string | null;
  instanceId: string;
  notice: string | null;
  revision: number;
  selection?: Selection;
  workspace: EditorWorkspaceInfo;
}

export interface EditorWorkspaceInfo {
  mapsPath: string;
  name: string;
}

export interface Group {
  id: string;
  layer: number;
  locked: boolean;
  name: string;
  parentId: string;
  visible: boolean;
}

export interface MapDocument {
  formatVersion: number;
  layerGroups: Group[];
  name: string;
  properties: Property[];
  rooms: Room[];
  stylegrounds: MapStyleground[];
  tileSize: number;
}

export interface MapObject {
  definition: string;
  groupId: string;
  height: number;
  id: string;
  layer: number;
  nodes: Point[];
  properties: Property[];
  rotation: number;
  scaleX: number;
  scaleY: number;
  width: number;
  x: number;
  y: number;
}

export interface MapStyleground {
  color: string;
  id: string;
  layer: number;
  name: string;
  properties: Property[];
  scrollX: number;
  scrollY: number;
  texture: string;
  type: string;
}

export interface Material {
  color: string;
  id: string;
  name: string;
  sprites: SpriteRect[];
  themeId: string | null;
}

export interface ObjectField {
  choices: string[];
  defaultValue: string;
  key: string;
  kind: number;
  label: string;
  max: number;
  min: number;
  required: boolean;
}

export interface Point {
  x: number;
  y: number;
}

export interface Property {
  key: string;
  value: string;
}

export interface Rect {
  height: number;
  width: number;
  x: number;
  y: number;
}

export interface Room {
  background: Cell[];
  foreground: Cell[];
  height: number;
  id: string;
  locked: boolean;
  name: string;
  objects: MapObject[];
  properties: Property[];
  visible: boolean;
  width: number;
  x: number;
  y: number;
}

export interface Selection {
  area: Rect | null;
  brushSize: number;
  filled: boolean;
  groupId: string;
  hiddenLayers: number[];
  layer: number;
  lockedLayers: number[];
  material: string;
  nodes: EditorNodeSelection[];
  objectDefinition: string;
  objects: string[];
  roomId: string | null;
  roomIds: string[];
  shape: number;
  tool: number;
}

export interface SpriteRect {
  asset: string;
  height: number;
  mask: number;
  shape: number;
  width: number;
  x: number;
  y: number;
}

export const TOOLS = ["Rooms","Placement","Selection","Brush","Rectangle","Bucket","Line","Circle","Ellipse"];
export const LAYERS = ["ForegroundTiles","BackgroundTiles","Entities","Triggers","ForegroundDecals","BackgroundDecals","All"];
export const SHAPES = ["Solid","BottomLeft","BottomRight","TopLeft","TopRight"];
export const MAX_BRUSH_SIZE = 16;
export const MAP_FORMAT_VERSION = 2;
export const TILE_SIZE = 16;
